# Generated by Django 2.1.4 on 2020-02-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('banner_image', models.URLField()),
                ('featured', models.BooleanField()),
                ('short_summary', models.CharField(max_length=200)),
                ('required_knowledge', models.TextField()),
                ('syllabus', models.TextField()),
                ('homepage', models.URLField()),
                ('summary', models.TextField()),
                ('faq', models.TextField()),
                ('level', models.CharField(max_length=50)),
                ('expected_duration_unit', models.CharField(max_length=50)),
                ('expected_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('display_title', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(to='catalog.Course')),
                ('skills', models.ManyToManyField(to='catalog.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(to='catalog.Lesson'),
        ),
    ]
